apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: zhiyong2-tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: zhiyong2-tanzu-java-web-app
spec:
  source:
    git:
      url: https://github.com/showpune/zhiyong2-tanzu-java-web-app
      ref:
        branch: master
